# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MisNotas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MisNotas
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/AdMob'
  pod 'Firebase/Invites'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  
end
